### PR TITLE
Use npmignore

### LINKED ISSUE #8: Error: Cannot find module 'laboratory'
Happens after upgrade to 1.0.0

Cheers

### PR DESCRIPTION
**Pull request by adborden**
Fixes #8, don't ignore /lib in npm publish.

### CODE REVIEW

**Comment by duereg** [comment]
Thanks @adborden! :)
