### ISSUE TITLE
Error: Cannot find module 'laboratory'

### ISSUE THREAD

**Issue by leandono** [duereg/laboratory#8]
Happens after upgrade to 1.0.0

Cheers

**Comment by duereg** [comment]
Can you give me more information? I can see the package on npm ... did you forget to run npm install after upgrading to the newest version?

**Comment by adborden** [comment]
The tarball doesn't have the compiled json in it :/

```
$ curl http://registry.npmjs.org/laboratory/-/laboratory-1.0.0.tgz | tar tzv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4043  100  4043    0     0   7367      0 --:--:-- --:--:-- --:--:--  7990
-rw-rw-r-- 1000/1000       669 2015-02-12 20:59 package/package.json
-rw-rw-r-- 1000/1000       102 2015-02-12 20:59 package/.npmignore
-rw-rw-r-- 1000/1000      1821 2015-02-12 20:59 package/README.md
-rw-rw-r-- 1000/1000      1071 2015-02-12 20:59 package/LICENSE
-rw-rw-r-- 1000/1000      3475 2015-02-12 20:59 package/spec/experiment.spec.coffee
-rw-rw-r-- 1000/1000      1592 2015-02-12 20:59 package/spec/laboratory.spec.coffee
-rw-rw-r-- 1000/1000       341 2015-02-12 20:59 package/.travis.yml
-rw-rw-r-- 1000/1000      1050 2015-02-12 20:59 package/src/experiment.coffee
-rw-rw-r-- 1000/1000       114 2015-02-12 20:59 package/src/index.coffee
-rw-rw-r-- 1000/1000       396 2015-02-12 20:59 package/src/laboratory.coffee
-rw-rw-r-- 1000/1000       273 2015-02-12 20:59 package/src/memory_store.coffee
```

Should get built as part of the publish... I think gitignore is getting in the way...

**Comment by adborden** [comment]
Oh, yeah, that's totally it https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by duereg** [comment]
@leandono this should be resolved in 1.0.1

**Comment by leandono** [comment]
Thanks ;)
